{"name": "test_div[div01]", "status": "failed", "statusDetails": {"message": "Failed: DID NOT RAISE <class 'ZeroDivisionError'>", "trace": "self = <test_calc.TestCalculator object at 0x000002CB53591730>\nget_instance = <calculatorcode.calculator.Calculator object at 0x000002CB53591F40>, get_datad_with_fixture = [56, 8, 7]\n\n    def test_div(self,get_instance,get_datad_with_fixture):\n        with pytest.raises(ZeroDivisionError):\n            rd = get_datad_with_fixture\n            print(f\"a={rd[0]},b={rd[1]},result={rd[2]}\")\n>           assert rd[2] == get_instance.div(rd[0], rd[1])\nE           Failed: DID NOT RAISE <class 'ZeroDivisionError'>\n\ntest_calc.py:98: Failed"}, "parameters": [{"name": "get_datad_with_fixture", "value": "[56, 8, 7]"}], "start": 1612688177419, "stop": 1612688177419, "uuid": "8e97bcd5-f436-4bc0-b961-5ba57c79edcd", "historyId": "b1bc78c816d60bfd646ffb13bcd24d8d", "testCaseId": "a5c3e315495f5a4462b01f5b10803462", "fullName": "test_calc.TestCalculator#test_div", "labels": [{"name": "feature", "value": "计算器"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-2CS9HKF"}, {"name": "thread", "value": "9092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc"}]}